#
# ---> light and self-made prompt <---
# branch=master mode=insert
# setopt promptsubst
# left side
# left=' %n 𝝙 %~'
# right side + beginning of input line
# PS1='%K{021}%F{123}$left${(l,COLUMNS-${#${(%)left}},)${${:-$(_git_repo_name) $(git_prompt_info) }//[%]/%%}}%f%k$(_prompt_char)'
# PS2='➤➤ '

# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# examples https://github.com/bhilburn/powerlevel9k/wiki/Show-Off-Your-Config



# GLOBAL

POWERLEVEL9K_MODE='nerdfont-complete'
ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_SHORTEN_DIR_LENGTH=30
POWERLEVEL9K_RAM_ELEMENTS=(ram_free)
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M}"


# CUSTOM ELEMENTS

POWERLEVEL9k_CUSTOM_GIT_REPO_NAME="zsh_show_git_repo_name"
POWERLEVEL9K_CUSTOM_INTERNET_SIGNAL="zsh_show_internet_signal"
POWERLEVEL9K_CUSTOM_ITUNES_TRACK="zsh_show_itunes_track"



# ICONS

POWERLEVEL9K_HOME_ICON=''
POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_FOLDER_ICON=''
POWERLEVEL9K_IP_ICON=''
# POWERLEVEL9K_BATTERY_ICON=''
# POWERLEVEL9K_HIDE_BRANCH_ICON=true

POWERLEVEL9K_VCS_GIT_ICON=''
POWERLEVEL9K_VCS_STAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_UNTRACKED_ICON='\u25CF'
POWERLEVEL9K_VCS_UNSTAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='\u2193'
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='\u2191'



# COLORS

POWERLEVEL9K_OS_ICON_BACKGROUND="021"
POWERLEVEL9K_OS_ICON_FOREGROUND="015"

POWERLEVEL9K_TIME_BACKGROUND="021"
POWERLEVEL9K_TIME_FOREGROUND="015"

POWERLEVEL9K_RAM_BACKGROUND="005"
POWERLEVEL9K_RAM_FOREGROUND="015"
POWERLEVEL9K_RAM_ELEMENTS=(ram_free)

POWERLEVEL9K_BATTERY_LOW_BACKGROUND="015"
POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND="015"
POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND="015"
POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND="015"
POWERLEVEL9K_BATTERY_LOW_FOREGROUND="001"
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND="093"
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND="021"
POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND="015"
POWERLEVEL9K_BATTERY_LOW_VISUAL_IDENTIFIER_COLOR="001"
POWERLEVEL9K_BATTERY_CHARGING_VISUAL_IDENTIFIER_COLOR="093"
POWERLEVEL9K_BATTERY_CHARGED_VISUAL_IDENTIFIER_COLOR="021"

POWERLEVEL9K_CUSTOM_INTERNET_SIGNAL_BACKGROUND="015"
POWERLEVEL9K_CUSTOM_INTERNET_SIGNAL_FOREGROUND="021"

POWERLEVEL9K_CUSTOM_GIT_REPO_NAME_BACKGROUND="000"
POWERLEVEL9K_CUSTOM_GIT_REPO_NAME_FOREGROUND="000"

POWERLEVEL9K_IP_BACKGROUND="021"
POWERLEVEL9K_IP_FOREGROUND="015"

POWERLEVEL9K_CUSTOM_ITUNES_TRACK_BACKGROUND="005"
POWERLEVEL9K_CUSTOM_ITUNES_TRACK_FOREGROUND="015"

POWERLEVEL9K_VCS_BACKGROUND="005"
POWERLEVEL9K_VCS_FOREGROUND="015"
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='005'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='015'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='005'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='226'

POWERLEVEL9K_NODE_VERSION_BACKGROUND='021'
POWERLEVEL9K_NODE_VERSION_FOREGROUND='118'



# SET PROMPTS

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="\\n \\n"
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX=" %K{015}%F{021}𝝙 %~ %f%k \n $(_prompt_char) "

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon ram node_version custom_git_repo_name)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vcs)

